name: Run tests
on: [push]
concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install NodeJS@16
        uses: actions/setup-node@v2
        with: 
          node-version: 16

      - name: Install essentials
        run: |
          sudo apt-get update;
          sudo apt-get install -yqq --no-install-recommends build-essential git wget ca-certificates curl unzip ninja-build ccache gnupg;
          
      - name: Install cmake
        run: |
          sudo apt remove --purge --auto-remove cmake; 
          sudo apt update; 
          sudo apt install -y software-properties-common lsb-release; 
          sudo apt clean all; 
          sudo wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null; 
          sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"; 
          sudo apt update; 
          sudo apt install cmake -yqq;
      
      - name: Install Mono (C#)
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF;
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list;
          sudo apt update;
          sudo apt install mono-complete -yqq;

      - name: Install other compilers
        run: |
          sudo apt-get update;
          sudo apt-get install -yqq --no-install-recommends cargo openjdk-17-jdk golang nodejs php-cli python3 ruby rustc;
          sudo rm -rf /var/lib/apt/lists/*;
          sudo apt-get autoremove -yqq;

      - name: Run tests
        run: |
          make test YEAR=2021 DAY=1;
          make test YEAR=2021 DAY=2;

      - name: Push new leaderboards
        run: |
          git add leaderboards/*
          git -c 'user.name=github-actions[bot]' -c 'user.email=41898282+github-actions[bot]@users.noreply.github.com' commit -m "Update leaderboards"
          git push
